### ISSUE TITLE
Error, Steam is missing

### ISSUE THREAD

**Issue by dagvdp** [bastimeyer/dayz-linux-cli-launcher#1]
Even though I have steam installed and changed the root directory of steam in the script, it says that Steam is missing.

**Comment by bastimeyer** [comment]
Apparently, it can't find the `steam` executable in the paths listed in your `PATH` env vars (run `which steam` to check).

This probably means that you're using the flatpak version of steam, which is not supported (yet).

**Comment by dagvdp** [comment]
Yeah, you were right. Installing steam from their website resolved the issue. Thanks

**Comment by bastimeyer** [comment]
Flatpak support implemented via a1c4643d6051106c877c2b7e44c2dce241ab3960

Steam must be running inside the flatpak container. If it's not available, then it'll fall back to the steam system package. A custom steam executable can also be set via `--steam`, or flatpak or non-flatpak mode enforced. See the updated README / help message output.
