### ISSUE TITLE
Fails to download mods required for server

### ISSUE THREAD

**Issue by Ronkn** [bastimeyer/dayz-linux-cli-launcher#12]
Issue: 
when using example provided in readme, to query the server and download necessary mods, then join; it is failing to download the mods. Please see  output at bottom

**this is the first time I've tried to use this feature. The server I've been playing on, I copied the downloaded files from my windows partition**

Version: 0.5.0
Steam: non-flatpak
Distro: PopOS 22.04

>./dayz-launcher.sh -d -l -s 51.81.48.48:2702 -p 27600 -n Frank

```
[dayz-launcher.sh][info] Resolving steam
[dayz-launcher.sh][info] Using non-flatpak mode: steam
[dayz-launcher.sh][debug] Checking directory: /home/bing/.steam/debian-installation/steamapps/common/DayZ
[dayz-launcher.sh][debug] Checking directory: /home/bing/.steam/debian-installation/steamapps/workshop/content/221100
[dayz-launcher.sh][info] Querying API for server: 51.81.48.48:27600
[dayz-launcher.sh][debug] Querying https://dayzsalauncher.com/api/v1/query/51.81.48.48/27600
[dayz-launcher.sh][debug] Parsing API response
[dayz-launcher.sh][error] Missing mods data from API response
```

**Comment by bastimeyer** [comment]
> [dayz-launcher.sh][debug] Querying https://dayzsalauncher.com/api/v1/query/51.81.48.48/27600
> [dayz-launcher.sh][debug] Parsing API response
> [dayz-launcher.sh][error] Missing mods data from API response

This is what the dayzsalauncher.com JSON API returns with the provided IP address and query port:

> ```json
> {"status":1,"error":"Timeout has occurred"}
> ```

As you can see, this is either a problem with the dayzsalauncher.com JSON API and/or your server, not the launcher script. Or you've used an invalid IP address and/or query port. Various server browsers don't list anything on this address.

**Comment by bastimeyer** [comment]
The query port is `27416`, not `27600`.

This yields the correct results:
https://dayzsalauncher.com/api/v1/query/51.81.48.48/27416
