### ISSUE TITLE
Connecting to servers without mods

### ISSUE THREAD

**Issue by mrebw** [bastimeyer/dayz-linux-cli-launcher#14]
Hi

Thanks for creating this project! I'm excited to finally get to (attempt to) play my favourite game on my favourite OS :)

Not entirely sure if this is an real issue or plain user error:
I'm trying to connect to a vanilla Cherno server that does not require any mods, which results in the following error:
`[dayz-launcher.sh][error] Missing mods data from API response`
Feels like the launcher can maybe not distinguish between an empty and a missing mods list? 
Server data at https://dayzsalauncher.com/api/v1/query/145.239.204.140/27016

Regards,
mrebw

**Comment by bastimeyer** [comment]
Fixed via feafd7460fa7929f10fbbee9fab873e1e667cc7d

https://github.com/bastimeyer/dayz-linux-cli-launcher/blob/0.5.1/CHANGELOG.md#051---2022-05-25

**Comment by mrebw** [comment]
Thanks for the super quick reply and fix!
Works like a charm!
