### ISSUE TITLE
alternative solution

### ISSUE THREAD

**Issue by WoozyMasta** [bastimeyer/dayz-linux-cli-launcher#19]
Hi

Thank you very much for this project, it helped me a lot when trying to play DayZ with friends.

But over time, I realized that I lacked the server browser, history, favorites and automatic installation of mods. And I tried to implement this in the project https://github.com/WoozyMasta/dayz-ctl

Perhaps it will be useful or interesting, so I decided to share it here

**Comment by bastimeyer** [comment]
Cool project, thanks for sharing.
You should however post this somewhere else instead of here, as it doesn't belong on this issue tracker.
