### ISSUE TITLE
Shell Script does not launch

### ISSUE THREAD

**Issue by UnholyKidd1** [bastimeyer/dayz-linux-cli-launcher#23]
Simply this, trying to run the sh file as a program results in a terminal opening for a split second, but then closing, no error message, nothing.
Attempt over Terminal ended like this: 
(base) snom@snom-All-Series:~/dayz-linux-cli-launcher$ bash dayz-launcher.sh
[dayz-launcher.sh][info] Resolving steam
[dayz-launcher.sh][info] Using non-flatpak mode: steam
[dayz-launcher.sh][error] Invalid/missing directory: /home/snom/.local/share/Steam/steamapps/common/DayZ

I have read in your other responses that you are supposed to use STEAM_ROOT, but frankly, I have no idea what it means since I am completely new to Linux and have no idea how anything works.

**Comment by bastimeyer** [comment]
> [dayz-launcher.sh][error] Invalid/missing directory: /home/snom/.local/share/Steam/steamapps/common/DayZ

Where's the game installed on your system?

You set environment variables like this:

- either for the current shell session and all of the processes that will be spawned
  https://www.gnu.org/software/bash/manual/bash.html#index-export
  ```sh
  export STEAM_ROOT="/path/to/your/steam/root/directory"
  ./dayz-launcher.sh ARGUMENTS...
  ```
- or for a specific process only
  ```sh
  STEAM_ROOT="/path/to/your/steam/root/directory" ./dayz-launcner.sh ARGUMENTS...
  ```
- or for a specific process only using the `env` utility (GNU coreutils) which can do more than just adding env vars
  https://www.gnu.org/software/coreutils/manual/html_node/env-invocation.html#env-invocation
  ```sh
  env STEAM_ROOT="/path/to/your/steam/root/directory" ./dayz-launcner.sh ARGUMENTS...
  ```

**Comment by UnholyKidd1** [comment]
It works now. I am gonna copy&paste what I needed to do:
```(base) snom@snom-All-Series:~$ export STEAM_ROOT=~/.steam/debian-installation
(base) snom@snom-All-Series:~$ cd dayz-linux-cli-launcher
(base) snom@snom-All-Series:~/dayz-linux-cli-launcher$ bash dayz-launcher.sh
[dayz-launcher.sh][info] Resolving steam
[dayz-launcher.sh][info] Using non-flatpak mode: steam
[dayz-launcher.sh][info] Nothing to do...
[dayz-launcher.sh][info] No mod-ID list, --server address, or --launch parameter set.
[dayz-launcher.sh][info] See --help for all the available options.
```

Last issues coming now are running DayZ on Steam in general :)
Thank you
