### ISSUE TITLE
Operation timed out after 10001 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by witmak38** [bastimeyer/dayz-linux-cli-launcher#4]
[dayz-launcher.sh][debug] Querying https://api.daemonforge.dev/server/185.189.255.141/2304/full
curl: (28) Operation timed out after 10001 milliseconds with 0 bytes received

**Comment by bastimeyer** [comment]
api.daemonforge.dev is a third party JSON API for querying DayZ servers, and it has some responsiveness/reliability issues. This however isn't something that can be fixed here. Just try running the launcher again until there is a propert API response.

As I said multiple times already, using this JSON API isn't ideal, but according to my research, it's the only one publicly available where the server's IP and query port can be set as parameters.

The best solution would be [querying the server directly](https://developer.valvesoftware.com/wiki/Server_queries) without using some kind of web API, but that is a bit difficult to achieve in a simple BASH script:
https://github.com/bastimeyer/dayz-linux-cli-launcher#todo
