### ISSUE TITLE
'gawk' is missing

### ISSUE THREAD

**Issue by sakulzz** [bastimeyer/dayz-linux-cli-launcher#7]
Hello today I wanted to install the dayz launcher. I followed the Install DayZ instructions and the Install instructions. 
I wanted to try it out but then this happend:
user@pop-os:~$ ./dayz-launcher.sh --launch
[dayz-launcher.sh][error] 'gawk' is missing (required for parsing the mod metadata). Aborting.

is there any fix for this?

PC specs (neofetch output):
![image](https://user-images.githubusercontent.com/96694137/147413753-9b966627-bf45-4038-a195-d1da803206ab.png)

**Comment by bastimeyer** [comment]
> is there any fix for this?

yes, you simply install gawk, because it is a dependency of the launcher
